---
title: "Shoe shopping"
description: |
 "These boots are made for shopping"

site: distill::distill_website
---

```{r setup, echo=F,include=F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
library(httr)
library(htmlwidgets)
library(distill)
library(lubridate)
library(dbplyr)
library(gganimate)
library(ggplot2)
library(ggiraph)
library(plotly)


#x<-read_csv("archive.zip") #male shoes
#y<-read_csv("7210_1.csv.zip") #female shoes
x <-read_csv("Copyarchive.zip")%>% 
  distinct(id, .keep_all= TRUE) %>% 
  select(dateadded,prices_amountmin,prices_amountmax,prices_currency,prices_issale) %>% 
  mutate(gender="Men") %>% 
  mutate(dateadded=as.Date(dateadded)) %>% 
  mutate(
         prices_amountmin=as.numeric(prices_amountmin),
         prices_amountmax=as.numeric(prices_amountmax)) %>%
  mutate(prices_issale=as.logical(prices_issale)) %>% 
  drop_na()

y <- read_csv("Copy7210_1.csv.zip")%>% 
  distinct(id, .keep_all= TRUE) %>% 
  select(dateAdded,prices.amountMin,prices.amountMax,prices.currency,prices.isSale) %>% 
  mutate(gender="Women") %>% 
  rename(prices_amountmin="prices.amountMin",prices_amountmax="prices.amountMax",prices_currency="prices.currency",prices_issale="prices.isSale") %>% 
  drop_na() %>% 
  mutate(dateadded=as.Date(dateAdded)) %>% 
  select(-dateAdded) %>% 
  drop_na()

shoes2<-full_join(x,y,by=c("dateadded", "prices_amountmin", "prices_amountmax", "prices_currency", "prices_issale", "gender"),copy=FALSE)

shoes3<-shoes2 %>% 
  mutate(price_avg=rowMeans(shoes2[c(2,3)],na.rm=T)) %>% 
  mutate(price_avg=round(price_avg,2)) %>%
  #select(-prices_amountmax,-prices_amountmin) %>% 
  filter(prices_currency=="USD") %>% 
  arrange(price_avg) %>% 
  filter(price_avg<=1000,price_avg>=10.00) %>% 
  select(-prices_currency)
shoes3$yearadded <- format(as.Date(shoes3$dateadded, format="%d/%m/%Y"),"%Y")
```


```{r graph, echo=F,include=T}

shoes3 %>%
  ggplot(mapping=aes(x=price_avg,fill=prices_issale,text = paste(
               "Price:", price_avg, "\n",
                          "Count",y)))+
  geom_histogram(bins=30,position="dodge")+
  facet_wrap(~gender)+
  theme_wsj()+
  labs(title="The shoe shopping tendencies of 10,000 \n men and 10,000 women from 2014 to 2017",subtitle="Women pay more for their shoes while men look for sales more",caption="Sources: Kaggle", x="Price (USD)",y="Count",fill="On sale?")+
  theme(text=element_text(size=8))+
  theme(axis.title=element_text(size=10))+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  theme(plot.title = element_text(size = 17))+
  theme(plot.subtitle = element_text(size = 13))+
  theme(legend.text = element_text(size = 10))+
  theme(legend.title = element_text(size = 12))+
  scale_fill_manual(values=c("darkgoldenrod1","#1b98e0"),label=(c("NO","YES")))+
  scale_y_continuous(breaks=c(200,400,600,800,1000,1200,1400,1600,1800,2000))
 
#ggplotly(shoes4,tooltip="text")
```
